# Generated by Django 3.2.12 on 2023-04-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='User',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps_is_html',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
    ]
